version: '3.7'

services:

  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dev#1234
      - MSSQL_PID=Express
    ports: 
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
